export { CRDTDocument } from './crdt';
export {
  identifyChord,
  analyzeChordProgression,
  getChordRootSemitone,
  getChordPitches,
  getChordNotePitches,
} from './chord-recognition';
export {
  PITCH_NAMES,
  JIANPU_MAP,
  DURATION_BEATS,
  DURATION_SYMBOLS,
  DURATION_LABELS,
  CRDT_WEIGHT,
  INTERPOLATION,
  ACCOMPANIMENT,
  pitchToFrequency,
  pitchToStaffPosition,
  staffPositionToPitch,
  snapToGrid,
  computeMergeScore,
  lerpNumber,
  easeOutCubic,
} from './types';
export type {
  Note,
  NotePitch,
  PitchName,
  Duration,
  Operation,
  OperationType,
  SyncMessage,
  ClientPosition,
  TrackType,
  OwnerRole,
  Chord,
  ChordQuality,
  AccompanimentPattern,
} from './types';
